name: contacts_permission_handler
description: "Contacts Permission Handler"
version: 0.0.1
homepage: https://github.com/okellogerald/flutter_contacts_permission_plugin

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.okello.contacts_permission_handler
        pluginClass: ContactsPermissionHandlerPlugin
      ios:
        pluginClass: ContactsPermissionHandlerPlugin
